# This workbench starts three commands in parallel. Printing three, two, one in
# that order to the standard output.

mode = "parallel"

[run.one]
cmd = ["bash", "-c", "sleep 0.2; echo one"]

[run.two]
cmd = ["bash", "-c", "sleep 0.1; echo two"]

[run.three]
cmd = ["bash", "-c", "sleep 0; echo three"]
