root: ./docs

structure:
  readme: readme.md
  summary: summary.md

redirects:
  dl: installation.md
  download: installation.md
  downloads: installation.md
  get: installation.md
  install: installation.md
  instal: installation.md
  instalation: installation.md
