[package]
name = "workbench"
version = "0.1.0"
authors = ["Aymeric Beaumet <hi@aymericbeaumet.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.1", features = ["derive"] }
indexmap = { version = "1.9.3", features = ["serde"] }
log = "0.4.17"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.159", features = ["derive"] }
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread", "signal", "fs", "process"] }
toml = "0.7.3"
uuid = { version = "1.3.0", features = ["v4"] }

[dev-dependencies]
assert_cmd = "2.0.10"
futures = "0.3.28"
glob = "0.3.1"
pretty_assertions = "1.3.0"

[profile.dev]
opt-level = 0

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
