[package]
name = "workbench"
version = "0.1.0"
authors = ["Aymeric Beaumet <hi@aymericbeaumet.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.1", features = ["derive"] }
log = "0.4.17"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.159", features = ["derive"] }
shell-words = "1.1.0"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread", "signal", "fs", "process"] }
toml = "0.7.3"
uuid = { version = "1.3.0", features = ["v4"] }

[profile.dev]
opt-level = 0

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
