# This run starts three commands in individual panels grouped under a
# unique tmux window.

mode = "tmux"

[[run]]
description = "fetch the current ip address"
cmd = ["curl", "icanhazip.com"]

[[run]]
cmd = ["uname", "-a"]

[[run]]
cmd = ["df", "-h"]
