# This run starts three commands in individual panels grouped under a
# unique tmux window.

mode = "tmux"

[run.curl]
description = "fetch the current ip address"
cmd = ["curl", "icanhazip.com"]

[run.uname]
cmd = ["uname", "-a"]

[run.df]
cmd = ["df", "-h"]
