# This workbench starts three commands in individual panels grouped under a
# unique tmux window.

mode = "tmux"

[[run]]
cmd = ["curl", "ifconfig.me"]

[[run]]
cmd = ["uname", "-a"]

[[run]]
cmd = ["df", "-h"]
