# This workbench starts three commands in individual panels grouped under a
# unique tmux window.

mode = "tmux"

[run.curl]
cmd = ["curl", "ifconfig.me"]

[run.uname]
cmd = ["uname", "-a"]

[run.df]
cmd = ["df", "-h"]
