# This workbench starts three commands in parallel. Printing three, two, one in
# that order to the standard output.

mode = "parallel"

[[run]]
cmd = ["bash", "-c", "sleep 2; echo one"]

[[run]]
cmd = ["bash", "-c", "sleep 1; echo two"]

[[run]]
cmd = ["bash", "-c", "sleep 0; echo three"]
