# Print three, two, one in that order.

mode = "parallel"

[[run]]
cmd = ["bash", "-c", "sleep 2; date '+%H:%M:%S one'"]

[[run]]
cmd = ["bash", "-c", "sleep 1; date '+%H:%M:%S two'"]

[[run]]
cmd = ["bash", "-c", "sleep 0; date '+%H:%M:%S three'"]
