# This run starts three commands sequentially. Printing one, two, three
# in that order to the standard output.

mode = "sequential"

[[run]]
name = "one"
cmd = ["bash", "-c", "echo one"]

[[run]]
name = "two"
cmd = ["bash", "-c", "echo two"]

[[run]]
name = "three"
cmd = ["bash", "-c", "echo three"]
