# This run starts three commands sequentially. Printing one, two, three
# in that order to the standard output.

mode = "sequential"

[run.one]
cmd = ["bash", "-c", "echo one"]

[run.two]
cmd = ["bash", "-c", "echo two"]

[run.three]
cmd = ["bash", "-c", "echo three"]
