# This run starts three commands sequentially. Printing one, two, three
# in that order to the standard output.

mode = "sequential"

[[run]]
cmd = ["bash", "-c", "echo one"]

[[run]]
cmd = ["bash", "-c", "echo two"]

[[run]]
cmd = ["bash", "-c", "echo three"]
