# This run starts three commands sequentially. Printing one, two, three
# in that order to the standard output.

mode = "sequential"

[[run]]
name = "one"
cmd = ["echo", "one"]

[[run]]
name = "two"
cmd = ["echo", "two"]

[[run]]
name = "three"
cmd = ["echo", "three"]
