# This workbench starts three commands sequentially. Printing one, two, three
# in that order to the standard output.

mode = "sequential"

[[run]]
cmd = ["bash", "-c", "sleep 1; echo one"]

[[run]]
cmd = ["bash", "-c", "sleep 1; echo two"]

[[run]]
cmd = ["bash", "-c", "sleep 1; echo three"]
