builds:
  - targets:
      # linux
      - linux_amd64
      - linux_arm64
      - linux_386
      # macos
      - darwin_amd64
      - darwin_arm64
      # windows
      - windows_amd64
      - windows_386
      # freebsd
      - freebsd_amd64
    hooks:
      post: ./postbuild

archives:
  - name_template: >-
      {{- .ProjectName }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "386" }}i686
      {{- else }}{{ .Arch }}{{ end }}-
      {{- if eq .Os "linux" }}unknown-linux-gnu
      {{- else if eq .Os "darwin" }}apple-darwin
      {{- else if eq .Os "windows" }}pc-windows-msvc
      {{- else if eq .Os "freebsd" }}unknown-freebsd
      {{- else }}{{ .Os }}{{ end -}}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
