# This workbench starts three commands sequentially. Printing one, two, three
# in that order to the standard output.

mode = "sequential" # this is the default and can be omitted

[[run]]
cmd = ["bash", "-c", "sleep 1; date '+%H:%M:%S one'"]

[[run]]
cmd = ["bash", "-c", "sleep 1; date '+%H:%M:%S two'"]

[[run]]
cmd = ["bash", "-c", "sleep 1; date '+%H:%M:%S three'"]
