# This run starts a bash process listening for SIGINT (sent on Ctrl-C)
# and printing a simple message on stdout when that happens. It's here to
# demonstrate run ability to properly forward signals.

[[run]]
cmd = ["bash", "-c", "echo 'Try to press Ctrl-C...'; trap 'echo Interrupted!' SIGINT; read"]
