name: ci

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "00 00 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: ${{ matrix.os == 'windows-latest' }}
        name: Windows Subsystem for Linux
        uses: Vampire/setup-wsl@v2

      - name: checkout
        uses: actions/checkout@v3

      - name: rustup
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt,clippy

      - name: cache
        uses: Swatinem/rust-cache@v2

      - name: cargo fmt
        run: cargo fmt --all --check --verbose

      - name: cargo clippy
        run: cargo clippy --all-targets --all-features --verbose -- --deny warnings

      - name: cargo build
        run: cargo build --all-targets --all-features --verbose

      - if: ${{ matrix.os == 'windows-latest' }}
        name: cargo test
        run: cargo test --all-targets --all-features --verbose
        shell: wsl-bash

      - if: ${{ matrix.os != 'windows-latest' }}
        name: cargo test
        run: cargo test --all-targets --all-features --verbose
