name: ci

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "00 00 * * *"

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: [rustfmt, clippy]

      - uses: Swatinem/rust-cache@v2

      - name: rustfmt
        run: cargo fmt --all --check --verbose

      - name: cargo clippy
        run: cargo clippy --all-targets --all-features --verbose -- --deny warnings

      - name: cargo build
        run: cargo build --all-targets --all-features --verbose

      - name: cargo test
        run: cargo test --all-targets --all-features --verbose
