name: ci

on:
  pull_request:
    branches: ["**"]
    paths-ignore: ["**/*.md"]
  push:
    branches: ["master"]
    paths-ignore: ["**/*.md"]
  schedule:
    - cron: "00 00 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Restore local binaries cache
        uses: actions/cache@v3
        with:
          path: .bin
          key: ${{ runner.os }}-${{ runner.arch }}-local-binaries

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt,clippy

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v2

      - name: cargo fmt
        run: cargo fmt --all --check --verbose

      - name: cargo clippy
        run: cargo clippy --all-targets --all-features --verbose -- --deny warnings

      - name: cargo build
        run: cargo build --all-targets --all-features --verbose

      - name: cargo test
        run: cargo test --all-targets --all-features --verbose
