name: release

on:
  push:
    tags:
      - "v*.*.*"
env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  release-crate:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: rustup
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: cache
        uses: Swatinem/rust-cache@v2

      - name: cargo publish
        run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
